version: '3'
services:
  web:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - 8080:8069
    volumes:
      - abhi-web:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - abhi-db:/var/lib/postgresql/data/pgdata
volumes:
  abhi-web:
  abhi-db:        

